trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: 'latest'

  - checkout: self  # Fetch code from GitHub

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az account show
      az account set --subscription 'a9abbc1e-f3f3-4acd-94f0-81d6b4d5289a'

  - script: |
      terraform init
      terraform plan -out=tfplan
    workingDirectory: Terraform
    displayName: 'Terraform Init & Plan'

  - script: |
      terraform apply -auto-approve tfplan
    workingDirectory: Terraform
    displayName: 'Terraform Apply'
