trigger:
  - main  # Runs when you push to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: tf_version
    value: '1.5.0'  # Adjust based on your Terraform version

steps:
  - checkout: self  # Clone your repo

  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: $(tf_version)

  - task: TerraformTaskV2@2
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: 'Terraform'
      backendServiceArm: '<Your-Service-Connection-Name>'

  - task: TerraformTaskV2@2
    displayName: 'Terraform Validate'
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: 'Terraform'

  - task: TerraformTaskV2@2
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: 'Terraform'
      environmentServiceNameAzureRM: '<Your-Service-Connection-Name>'

  - task: TerraformTaskV2@2
    displayName: 'Terraform Apply'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: 'Terraform'
      environmentServiceNameAzureRM: 'AzureServiceConnection'
      commandOptions: '-auto-approve'
